#if UNITY_IOS || UNITY_TVOS || UNITY_VISIONOS
using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

// Apple.Core's "Embed Apple Plug-in Libraries" Run Script phase intentionally
// skips .dSYM files (see AppleBuild.cs:GenerateEmbedNativeLibraryShellScript).
// As a result, dSYMs sit on disk under $PROJECT_DIR/ApplePluginLibraries/<Plugin>/
// but never reach the archive's dSYMs/ folder, so App Store Connect rejects
// the symbol upload for AppleCoreNative.framework and GameKitWrapper.framework.
//
// This post-processor adds an additional Run Script build phase that copies
// every .dSYM under ApplePluginLibraries into $DWARF_DSYM_FOLDER_PATH (which
// Xcode points at the archive's dSYMs/ folder during archive builds).
public static class AppleDSYMArchivePostProcess
{
    private const string PhaseName = "Copy Apple Plug-in dSYMs to Archive";

    // Apple.Core uses PostProcessBuild(10). Run after it so our phase lands
    // in the pbxproj that Apple.Core has finished writing.
    [PostProcessBuild(20)]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string pathToBuiltProject)
    {
        if (buildTarget != BuildTarget.iOS
            && buildTarget != BuildTarget.tvOS
#if UNITY_2022_3_OR_NEWER
            && buildTarget != BuildTarget.VisionOS
#endif
            )
        {
            return;
        }

        string pbxPath = PBXProject.GetPBXProjectPath(pathToBuiltProject);
        if (!File.Exists(pbxPath))
        {
            Debug.LogWarning($"[AppleDSYMArchivePostProcess] pbxproj not found at {pbxPath}");
            return;
        }

        // Dedup: on Append builds the post-processor runs against the existing
        // pbxproj. Skip if our phase is already present.
        string pbxText = File.ReadAllText(pbxPath);
        if (pbxText.Contains(PhaseName))
        {
            return;
        }

        var pbx = new PBXProject();
        pbx.ReadFromFile(pbxPath);

        string mainTargetGuid = pbx.GetUnityMainTargetGuid();
        pbx.AddShellScriptBuildPhase(mainTargetGuid, PhaseName, "/bin/sh", BuildScript());
        pbx.WriteToFile(pbxPath);

        Debug.Log("[AppleDSYMArchivePostProcess] Added dSYM archive copy phase to Unity-iPhone target.");
    }

    private static string BuildScript()
    {
        return string.Join("\n",
            "# Copies Apple Unity plug-in dSYMs into the archive's dSYMs folder.",
            "# Apple.Core's embed script skips dSYMs; this phase backfills them so",
            "# App Store Connect symbol upload succeeds for AppleCoreNative.framework",
            "# and GameKitWrapper.framework. Generated by AppleDSYMArchivePostProcess.cs.",
            "set -eu",
            "if [ -z \"${DWARF_DSYM_FOLDER_PATH:-}\" ]; then",
            "    echo \"DWARF_DSYM_FOLDER_PATH not set — skipping dSYM copy.\"",
            "    exit 0",
            "fi",
            "SRC_ROOT=\"$PROJECT_DIR/ApplePluginLibraries\"",
            "if [ ! -d \"$SRC_ROOT\" ]; then",
            "    echo \"$SRC_ROOT not found — nothing to do.\"",
            "    exit 0",
            "fi",
            "mkdir -p \"$DWARF_DSYM_FOLDER_PATH\"",
            "find \"$SRC_ROOT\" -type d -name '*.dSYM' -print0 | while IFS= read -r -d '' dsym; do",
            "    name=$(basename \"$dsym\")",
            "    dst=\"$DWARF_DSYM_FOLDER_PATH/$name\"",
            "    echo \"Copying $dsym -> $dst\"",
            "    rm -rf \"$dst\"",
            "    ditto \"$dsym\" \"$dst\"",
            "done"
        );
    }
}
#endif
